spring.application.name=FrozenPOS
spring.datasource.url=jdbc:mysql://localhost:3310/frozenpos_db
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=9090

jwt.secret-key=your-256-bit-secret-key-here-must-be-long-enough-for-hs256
